work_main_site:
    resource: "@WorkMainSiteBundle/Resources/config/routing.yml"
    prefix:   /

work_main_site_login:
    path:     /login
    defaults: { _controller: WorkMainSiteBundle:User:login }

work_main_site_login_check:
    path: /login_check

work_main_site_logout:
    path: /logout
    
_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout

fos_facebook_channel:
    resource: "@FOSFacebookBundle/Resources/config/routing.xml"