work_main_site_homepage:
    pattern:  /
    defaults: { _controller: WorkMainSiteBundle:WebApp:index }

login:
    pattern: /login
    defaults: { _controller: WorkMainSiteBundle:User:login }

work_main_site_register:
    pattern: /user/register
    defaults: { _controller: WorkMainSiteBundle:User:register }

work_main_site_companies:
    pattern: /companies
    defaults: { _controller: WorkMainSiteBundle:WebApp:companies }

work_main_site_candidates:
    pattern: /candidates
    defaults: { _controller: WorkMainSiteBundle:WebApp:candidates }

work_main_site_jobs:
    pattern: /jobs
    defaults: { _controller: WorkMainSiteBundle:WebApp:jobs }

work_main_site_about:
    pattern: /about
    defaults: { _controller: WorkMainSiteBundle:WebApp:about }

work_main_site_contact:
    pattern: /contact
    defaults: { _controller: WorkMainSiteBundle:WebApp:contact }

work_main_site_reviews:
    pattern: /reviews
    defaults: { _controller: WorkMainSiteBundle:WebApp:reviews }
    
work_main_site_post:
    pattern: /fb
    defaults: { _controller: WorkMainSiteBundle:Parse:index }

work_main_site_post_dashboard:
    pattern: /fb/dashboard
    defaults: { _controller: WorkMainSiteBundle:Parse:dashboard }