work_main_site_homepage:
    pattern:  /
    defaults: { _controller: WorkMainSiteBundle:WebApp:index }
login:
    pattern: /login
    defaults: { _controller: WorkMainSiteBundle:User:login }

index:
    pattern: /index
    defaults: { _controller: WorkMainSiteBundle:WebApp:index }
